# Generated by Django 5.2.8 on 2025-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrgScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members', models.IntegerField()),
                ('active_researchers', models.IntegerField()),
                ('regional_chapters', models.IntegerField()),
                ('schools_connected', models.IntegerField()),
            ],
        ),
    ]
