# Generated by Django 5.2.8 on 2025-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
