# Generated by Django 5.2.8 on 2025-11-18 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
