# Generated by Django 5.2.8 on 2025-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teammember_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
